/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01.gradle;

/**
 *
 *  Example usage custom class
 */
public class App {
    public static void main(String... args) {
        System.out.println("This message from main");
    }
}
