/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloOtusTest {
    @Test 
    public void testSomeLibraryMethod() {
        HelloOtus helloOtus= new HelloOtus();
        assertTrue(helloOtus.someMethod());
    }
}
